version: '3.4'

services:
  apitemplatecrawler:
    image: apitemplatecrawler
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    volumes: 
      - ./:/app
    ports:
      - 3000:3000
