name: Dev Deployment 
on:
  push:
    branches:
      - dev

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
       - 
        name: Checkout 
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build Image 
        run: docker build -t us-central1-docker.pkg.dev/deployment-helper-dev/api-template-crawler/api-template-crawler:dev .
      - 
        name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - 
        name: Use gcloud CLI
        run: gcloud info
      - 
        name: Docker GCP artifact login
        run: gcloud auth configure-docker us-central1-docker.pkg.dev 
      - 
        name: Push Docker image to GCP artifacts
        run: docker push us-central1-docker.pkg.dev/deployment-helper-dev/api-template-crawler/api-template-crawler:dev
      - 
        name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: us-central1-docker.pkg.dev/deployment-helper-dev/api-template-crawler/api-template-crawler:dev
          service: api-template-crawler
          credentials: ${{ secrets.GCP_SA_KEY }}

      